SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS SHOP_USER;
CREATE TABLE SHOP_USER (
ROW_ID INTEGER NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(50) NOT NULL,
PASS_WORD VARCHAR(50) NOT NULL,
IS_DELETED VARCHAR(20) NOT NULL,
PRIMARY KEY (ROW_ID)
);

DROP TABLE IF EXISTS SHOP_USER_DETAILS;
CREATE TABLE SHOP_USER_DETAILS (
ROW_ID INTEGER NOT NULL AUTO_INCREMENT,
EMAIL_ID VARCHAR(100) NOT NULL,
MOBILE VARCHAR(40) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
USER_ID INTEGER,
IS_DELETED VARCHAR(20) NOT NULL,
PRIMARY KEY (ROW_ID),
FOREIGN KEY(ROW_ID)  REFERENCES SHOP_USER(ROW_ID)
);